"""
GitHub service for applying infrastructure recommendations via PR.
Uses PyGithub to create a branch, commit the changed files, and open a PR.
"""
import logging
from typing import List, Dict, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


def apply_recommendation_as_pr(
    github_token: str,
    repo_full_name: str,
    base_branch: str,
    recommendation_title: str,
    recommendation_id: str,
    file_changes: List[Dict],  # list of {file_path, new_content, action}
) -> Optional[str]:
    """
    Creates a new branch, commits all file changes, and opens a PR.
    Returns the PR URL, or raises an exception on failure.
    """
    try:
        from github import Github, GithubException
    except ImportError:
        raise RuntimeError("PyGithub is not installed. Add 'PyGithub' to requirements.txt")

    import os
    token = github_token
    env_token = os.getenv("GITHUB_TOKEN")
    if env_token and env_token.strip():
        logger.info("Using system-wide GITHUB_TOKEN override from environment")
        token = env_token.strip()

    g = Github(token)
    repo = g.get_repo(repo_full_name)

    # 1. Create branch name
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    safe_title = recommendation_title.lower().replace(" ", "-")[:40]
    branch_name = f"codelens/infra/{safe_title}-{timestamp[:8]}"

    logger.info(f"Creating branch '{branch_name}' from '{base_branch}' in {repo_full_name}")

    # 2. Get base branch SHA
    base_ref = repo.get_branch(base_branch)
    base_sha = base_ref.commit.sha

    # 3. Create new branch (with fallback to fork if write access is denied)
    target_repo = repo
    head_spec = branch_name
    use_fork = False

    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
    except GithubException as e:
        if e.status == 403:
            logger.info("Write access denied (403). Attempting to fork and apply recommendation via fork...")
            use_fork = True
        elif e.status == 422:  # branch already exists
            logger.warning(f"Branch {branch_name} already exists, continuing")
        else:
            raise

    if use_fork:
        try:
            # Fork the repository
            fork = repo.create_fork()
            logger.info(f"Fork created successfully: {fork.full_name}")
            target_repo = fork
            head_spec = f"{fork.owner.login}:{branch_name}"
            
            # Re-read base branch sha from fork
            import time
            for _ in range(5): # wait up to 5s for fork to be ready
                try:
                    fork_base_ref = fork.get_branch(base_branch)
                    base_sha = fork_base_ref.commit.sha
                    break
                except GithubException:
                    time.sleep(1)
            
            # Create branch on fork
            try:
                fork.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
            except GithubException as fe:
                if fe.status != 422:
                    raise
        except Exception as fork_err:
            logger.error(f"Fork workflow failed: {fork_err}")
            raise RuntimeError(f"Cannot write directly to {repo_full_name} and fork workflow failed: {fork_err}")

    # 4. Commit each file change to target_repo (either parent repo or fork)
    pr_body_lines = [
        f"## 🤖 CodeLens AI Infrastructure Recommendation",
        f"",
        f"**{recommendation_title}**",
        f"",
        f"This PR was automatically generated by the CodeLens Infrastructure Engine.",
        f"",
        f"### Changes Made",
    ]

    for change in file_changes:
        file_path = change["file_path"]
        new_content = change["new_content"]
        action = change.get("action", "modify")
        diff_summary = change.get("diff_summary", "")

        pr_body_lines.append(f"- **`{file_path}`** ({action}): {diff_summary}")

        commit_message = f"chore(infra): {diff_summary or recommendation_title}\n\nGenerated by CodeLens AI (rec-id: {recommendation_id})"

        try:
            if action == "create":
                # Create new file
                target_repo.create_file(
                    path=file_path,
                    message=commit_message,
                    content=new_content,
                    branch=branch_name,
                )
                logger.info(f"Created file {file_path}")
            elif action in ("modify", "update"):
                # Get existing file and update it
                try:
                    existing = target_repo.get_contents(file_path, ref=branch_name)
                    target_repo.update_file(
                        path=file_path,
                        message=commit_message,
                        content=new_content,
                        sha=existing.sha,
                        branch=branch_name,
                    )
                    logger.info(f"Updated file {file_path}")
                except GithubException:
                    # File doesn't exist yet — create it
                    target_repo.create_file(
                        path=file_path,
                        message=commit_message,
                        content=new_content,
                        branch=branch_name,
                    )
                    logger.info(f"Created (new) file {file_path}")
            elif action == "delete":
                try:
                    existing = target_repo.get_contents(file_path, ref=branch_name)
                    target_repo.delete_file(
                        path=file_path,
                        message=commit_message,
                        sha=existing.sha,
                        branch=branch_name,
                    )
                    logger.info(f"Deleted file {file_path}")
                except Exception:
                    logger.warning(f"Could not delete {file_path} — it may not exist")
        except Exception as e:
            logger.error(f"Error applying change to {file_path}: {e}")
            raise

    # 5. Open the PR on the parent repo
    pr_body = "\n".join(pr_body_lines)
    pr_body += f"\n\n---\n*Recommendation ID: `{recommendation_id}`*\n*Generated by [CodeLens](https://github.com)*"

    pr = repo.create_pull(
        title=f"[CodeLens] {recommendation_title}",
        body=pr_body,
        head=head_spec,
        base=base_branch,
    )

    logger.info(f"Created PR: {pr.html_url}")
    g.close()

    return pr.html_url
