"""
GitHub service for applying infrastructure recommendations via PR.
Uses PyGithub to create a branch, commit the changed files, and open a PR.
"""
import logging
from typing import List, Dict, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


def apply_recommendation_as_pr(
    github_token: str,
    repo_full_name: str,
    base_branch: str,
    recommendation_title: str,
    recommendation_id: str,
    file_changes: List[Dict],  # list of {file_path, new_content, action}
) -> Optional[str]:
    """
    Creates a new branch, commits all file changes, and opens a PR.
    Returns the PR URL, or raises an exception on failure.
    """
    try:
        from github import Github, GithubException
    except ImportError:
        raise RuntimeError("PyGithub is not installed. Add 'PyGithub' to requirements.txt")

    g = Github(github_token)
    repo = g.get_repo(repo_full_name)

    # 1. Create branch name
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    safe_title = recommendation_title.lower().replace(" ", "-")[:40]
    branch_name = f"codelens/infra/{safe_title}-{timestamp[:8]}"

    logger.info(f"Creating branch '{branch_name}' from '{base_branch}' in {repo_full_name}")

    # 2. Get base branch SHA
    base_ref = repo.get_branch(base_branch)
    base_sha = base_ref.commit.sha

    # 3. Create new branch
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
    except GithubException as e:
        if e.status == 422:  # branch already exists
            logger.warning(f"Branch {branch_name} already exists, continuing")
        else:
            raise

    # 4. Commit each file change
    pr_body_lines = [
        f"## 🤖 CodeLens AI Infrastructure Recommendation",
        f"",
        f"**{recommendation_title}**",
        f"",
        f"This PR was automatically generated by the CodeLens Infrastructure Engine.",
        f"",
        f"### Changes Made",
    ]

    for change in file_changes:
        file_path = change["file_path"]
        new_content = change["new_content"]
        action = change.get("action", "modify")
        diff_summary = change.get("diff_summary", "")

        pr_body_lines.append(f"- **`{file_path}`** ({action}): {diff_summary}")

        commit_message = f"chore(infra): {diff_summary or recommendation_title}\n\nGenerated by CodeLens AI (rec-id: {recommendation_id})"

        try:
            if action == "create":
                # Create new file
                repo.create_file(
                    path=file_path,
                    message=commit_message,
                    content=new_content,
                    branch=branch_name,
                )
                logger.info(f"Created file {file_path}")
            elif action in ("modify", "update"):
                # Get existing file and update it
                try:
                    existing = repo.get_contents(file_path, ref=branch_name)
                    repo.update_file(
                        path=file_path,
                        message=commit_message,
                        content=new_content,
                        sha=existing.sha,
                        branch=branch_name,
                    )
                    logger.info(f"Updated file {file_path}")
                except GithubException:
                    # File doesn't exist yet — create it
                    repo.create_file(
                        path=file_path,
                        message=commit_message,
                        content=new_content,
                        branch=branch_name,
                    )
                    logger.info(f"Created (new) file {file_path}")
            elif action == "delete":
                try:
                    existing = repo.get_contents(file_path, ref=branch_name)
                    repo.delete_file(
                        path=file_path,
                        message=commit_message,
                        sha=existing.sha,
                        branch=branch_name,
                    )
                    logger.info(f"Deleted file {file_path}")
                except Exception:
                    logger.warning(f"Could not delete {file_path} — it may not exist")
        except Exception as e:
            logger.error(f"Error applying change to {file_path}: {e}")
            raise

    # 5. Open the PR
    pr_body = "\n".join(pr_body_lines)
    pr_body += f"\n\n---\n*Recommendation ID: `{recommendation_id}`*\n*Generated by [CodeLens](https://github.com)*"

    pr = repo.create_pull(
        title=f"[CodeLens] {recommendation_title}",
        body=pr_body,
        head=branch_name,
        base=base_branch,
    )

    logger.info(f"Created PR: {pr.html_url}")
    g.close()

    return pr.html_url
